config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'

  resources :conversations do
    resources :messages
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/user' => 'users#show'
  delete '/user' => 'users#destroy'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user1, :foreign_key => :user1_id, class_name: 'User'
  belongs_to :user2, :foreign_key => :user2_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :user1_id, :scope => :user2_id

  scope :between, -> (user1_id, user2_id) do
    where("(conversations.user1_id = ? AND conversations.user2_id = ?) OR (conversations.user1_id = ? AND conversations.user2_id = ?)", user1_id, user2_id, user2_id, user1_id)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true
  before_save :encrypt_password


  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/conversations_controller.rb
class ConversationsController < ApplicationController

  # before_action :authorize

  def index
    respond_with Conversation.all
  end

  # def create
  #   if Conversation.between(params[:user1_id], params[:user2_id]).present?
  #     @conversation = Conversation.between(params[:user1_id],
  #       params[:user2_id]).first
  #   else
  #     @conversation = Conversation.create!(conversation_params)
  #   end
  #   redirect_to conversation_messages_path(@conversation)
  # end

  private
  def conversation_params
    params.permit(:user1_id, :user2_id)
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController

  # before_action :authorize, only: [:show, :destroy]


  def index
    respond_with User.all
  end

  # def new
  #   @user = User.new
  # end
  #
  # def create
  #   if @user = User.new(user_params)
  #     if @user.save
  #       flash[:notice] = "You've successfully signed up!"
  #       session[:user_id] = @user.id
  #       redirect_to "/"
  #     else
  #       flash[:alert] = "There was a problem signing up."
  #       render :new
  #     end
  #   else
  #     flash[:alert] = "There was a problem signing up. Try clearing your cookies and trying again"
  #     render :new
  #   end
  # end
  #
  # def show
  #   @user = User.find(session[:user_id])
  #   render :show
  # end
  #
  # def destroy
  #   @user = User.find(session[:user_id])
  #   @user.destroy
  #   session[:user_id] = nil
  #   redirect_to '/'
  # end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :json

  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
    if session[:user_id]
      return @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You need to sign in."
      redirect_to '/'
    end
  end

  def authorize_conversation(user, conversation)
    if current_user.id != conversation.user1_id && current_user.id != conversation.user2_id
      flash[:alert] = 'You are not authorized to access that feature.'
      redirect_to '/'
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :authorize

  def index
    @user = User.find(session[:user_id])
    @users = User.all
    @conversations = Conversation.where("user1_id = ? OR user2_id = ?", @user.id, @user.id)
    # conversations = [{user1_id: 1, user2_id: 2}, {user1_id: 3, user2_id: 4}]
    render :index
  end

  def create
    if Conversation.between(params[:user1_id], params[:user2_id]).present?
      @conversation = Conversation.between(params[:user1_id],
        params[:user2_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private
  def conversation_params
    params.permit(:user1_id, :user2_id)
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
    @conversation = Conversation.find(params[:conversation_id])
    @user = User.find(session[:user_id])
    authorize_conversation(@user, @conversation)
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      reset_session
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      current_time = Time.new
      session[:updated_at] = current_time
      redirect_to "/conversations"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show, :destroy]

  def new
    @user = User.new
  end

  def create
    if @user = User.new(user_params)
      if @user.save
        flash[:notice] = "You've successfully signed up!"
        session[:user_id] = @user.id
        redirect_to "/"
      else
        flash[:alert] = "There was a problem signing up."
        render :new
      end
    else
      flash[:alert] = "There was a problem signing up. Try clearing your cookies and trying again"
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
    render :show
  end

  def destroy
    @user = User.find(session[:user_id])
    @user.destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/conversations/index.html.erb
<h1>Mailbox</h1>

<% if @conversations %>
  <% @conversations.each do |conversation| %>
    <% if conversation.user1_id == @user.id %>
      <p><% user2 = User.find(conversation.user2_id) %></p>
    <% elsif conversation.user2_id == @user.id %>
      <p><% user2 = User.find(conversation.user1_id) %></p>
    <% end %>
    <p><%= link_to user2.username, conversation_messages_path(conversation) %></p>
  <% end %>
<% end %>

<h2>Users</h2>
<% if @users %>
  <% @users.each do |user| %>
    <% if user.id != @user.id %>
      <p><%= user.username %> <%= link_to 'Message me!', conversations_path(user1_id: current_user.id, user2_id: user.id), method: 'post'%></p>
    <% end %>
  <% end %>
<% end %>

app/views/homepage/index.html.erb
<%= react_component 'Main' %>

app/views/layouts/_errors.html.erb
<% if @object %>
  <% if @object.errors.any? %>
    <p>Please fix these errors:</p>
      <% @object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
  <% end %>
<% end %>

app/views/layouts/_nav_bar.html.erb
<div>
  <p><a href="/">Home |</a>
  <span><%= link_to "Sign out", '/signout' %> |</span>
  <span><%= link_to "Chat", '/conversations' %> |</span>
  <span><%= link_to "Sign up", '/signup' %> |</span>
  <span><%= link_to "Sign in", '/signin' %></span>
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <%# <%= javascript_pack_tag 'Index' %>
  </head>

  <body>
    <%= render "layouts/nav_bar" %>
    
    <%= flash[:notice] %>
    <%= flash[:alert] %>

    <%= yield %>

  </body>
</html>

app/views/messages/index.html.erb
<% if @over_ten %>
  <%= link_to 'Show Previous', '?m=all' %>
<% end %>

<div>

  <% if current_user.id == @conversation.user1_id %>
    <p>Messages to <%= User.find(@conversation.user2_id).username %></p>
  <% else %>
    <p>Messages to <%= User.find(@conversation.user1_id).username %></p>
  <% end %>

  <% if @messages %>
    <% @messages.each do |message| %>
      <% if message.body %>
        <% user = User.find(message.user_id) %>
        <% if user.username == current_user.username %>
          <% class_name = "me d-flex justify-content-end" %>
        <% else %>
          <% class_name = "you d-flex justify-content-start" %>
        <% end %>
        <div class="<%= class_name %>">
        <p><%= message.body %></p>
      </div>
      <% end %>
    <% end %>
  <% end %>

  <%= form_for [@conversation, @message] do |f| %>
    <p><%= f.text_area :body %></p>
    <p><%= f.text_field :user_id, value: current_user.id, type: "hidden" %></p>
    <p><%= f.submit "Send" %></p>
  <% end %>

</div>

app/views/users/index.html.erb
<h1>Users</h1>

<% if @users.any? %>
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.username, user_path(user) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no users yet.</p>
<% end %>

app/views/users/new.html.erb
<%= render "layouts/errors", :object => @user %>

<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Username" %>
  <%= f.text_field :username %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Your Profile</h1>
<p>Name: <%= @user.username %></p>
<p>Email: <%= @user.email %></p>

<p><%= link_to "Delete your profile", user_path(@user),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>